[WARNING]
--
* Cannot read file './test.turi' from any of the directories:  at /Users/verhasp/github/turicum/clifx/REFERENCE.adoc.jam[include]/60:27
--
= Turicum Programming Language CLI with FX Reference

This document is the reference document for the Turicum programming language GUI Interface.

== Installation

You can find the installation kits at

    https://github.com/turicum-pl/turicum-pl.github.io/tree/main/download


The kit ``turicum-``__os__``-``__platform__``+-+``__version__``.zip`` is the installation kit, where

* __os__ operating system, `linux`, `windows` or `macos`,

* __platform__ is `x64` for Intel architecture, `arm64` for arm architecture,

* __version__ is the version of the software.

== Executing a script

After the installation, you can execute any script using the `turi` command.
You can also add

    #!/usr/local/bin/turifx

shebang line to the start of the script file.
The extension of the script file containing the Turicum source code has to have `.turi` extension.

To import files, you have to

* define the environment variable `APPIA`, or
* create an `.env` file or
* use the command line option `-APPIA`.

== REPL functionality

To start the interpreter in REPL mode use the option

    -REPL

like

    $ turi -REPL
    Turicum REPL with JLine (//help for more info)
    >>>

The prompt `>>>` is the REPL prompt.
You can enter any Turicum code or REPL commands.
REPL commands start with double `//`, which is a comment in Turicum.
The most important REPL commands are `//help` and `//exit`.

When the REPL application feels that you need to provide more code after the end of the line, it will prompt it with `...`.

== Compiling and Saving binaries

You can create a binary version of the code using the command line option `-compile`.

In the cli source code directory there is a file `{%@def test_source=test.turi%}`.

[WARNING]
--
* Cannot read file './test.turi' from any of the directories:  at /Users/verhasp/github/turicum/clifx/REFERENCE.adoc.jam[include]/60:27
--
    {%#include [verbatim] ./{%test_source%}%}

The command line

    turi -compile {%test_source%}

will create the file `test.turc`.
Executing this file with the command

    turi test.turc

will skip the source code compilation phase and will start the execution of the program.

    $ cat test.turi
    println "Hello, World!"
    $ turi -compile test.turi
    $ turi test.turi
    Hello, World!
    $ turi test.turc
    Hello, World!
    $
[WARNING]
--
* Cannot read file './test.turi' from any of the directories:  at /Users/verhasp/github/turicum/clifx/REFERENCE.adoc.jam[include]/60:27
--
[source]
----
Cannot read file './test.turi' from any of the directories:  at /Users/verhasp/github/turicum/clifx/REFERENCE.adoc.jam[include]/60:27
	javax0.jamal.tools.FileTools(getInput:119)
	javax0.jamal.builtins.Include(getInputOptional:91)
	javax0.jamal.builtins.Include(evaluate:56)
	javax0.jamal.engine.Processor(evaluateBuiltinMacro:523)
	javax0.jamal.engine.Processor(lambda$evaluateBuiltInMacro$6:463)
	javax0.jamal.engine.Processor(safeEvaluate:472)
	javax0.jamal.engine.Processor(evaluateBuiltInMacro:463)
	javax0.jamal.engine.Processor(evalMacro:412)
	javax0.jamal.engine.Processor(processMacro:325)
	javax0.jamal.engine.Processor(process:202)
	javax0.jamal.asciidoc.JamalPreprocessor(processJamal:451)
	javax0.jamal.asciidoc.JamalPreprocessor(runJamalInProcess:288)
	javax0.jamal.asciidoc.JamalPreprocessor(process:205)
Suppressed exceptions:
Cannot get the content of the file '/Users/verhasp/github/turicum/clifx/test.turi'	javax0.jamal.tools.FileTools(getFileContent:201)
	javax0.jamal.tools.FileTools(getInput:134)
	javax0.jamal.tools.FileTools(getInput:113)
	javax0.jamal.builtins.Include(getInputOptional:91)
	javax0.jamal.builtins.Include(evaluate:56)
	javax0.jamal.engine.Processor(evaluateBuiltinMacro:523)
	javax0.jamal.engine.Processor(lambda$evaluateBuiltInMacro$6:463)
	javax0.jamal.engine.Processor(safeEvaluate:472)
	javax0.jamal.engine.Processor(evaluateBuiltInMacro:463)
	javax0.jamal.engine.Processor(evalMacro:412)
	javax0.jamal.engine.Processor(processMacro:325)
	javax0.jamal.engine.Processor(process:202)
	javax0.jamal.asciidoc.JamalPreprocessor(processJamal:451)
	javax0.jamal.asciidoc.JamalPreprocessor(runJamalInProcess:288)
	javax0.jamal.asciidoc.JamalPreprocessor(process:205)
Causing Exception:
java.nio.file.NoSuchFileException: /Users/verhasp/github/turicum/clifx/test.turi	javax0.jamal.tools.FileTools(lambda$getFileContent$5:194)
	javax0.jamal.tools.FileTools(getFileContent:190)
	javax0.jamal.tools.FileTools(getInput:134)
	javax0.jamal.tools.FileTools(getInput:113)
	javax0.jamal.builtins.Include(getInputOptional:91)
	javax0.jamal.builtins.Include(evaluate:56)
	javax0.jamal.engine.Processor(evaluateBuiltinMacro:523)
	javax0.jamal.engine.Processor(lambda$evaluateBuiltInMacro$6:463)
	javax0.jamal.engine.Processor(safeEvaluate:472)
	javax0.jamal.engine.Processor(evaluateBuiltInMacro:463)
	javax0.jamal.engine.Processor(evalMacro:412)
	javax0.jamal.engine.Processor(processMacro:325)
	javax0.jamal.engine.Processor(process:202)
	javax0.jamal.asciidoc.JamalPreprocessor(processJamal:451)
	javax0.jamal.asciidoc.JamalPreprocessor(runJamalInProcess:288)
	javax0.jamal.asciidoc.JamalPreprocessor(process:205)
Causing Exception:
/Users/verhasp/github/turicum/clifx/test.turi	javax0.jamal.tools.FileInput(getInput:20)
	javax0.jamal.tools.FileTools(lambda$getFileContent$5:192)
	javax0.jamal.tools.FileTools(getFileContent:190)
	javax0.jamal.tools.FileTools(getInput:134)
	javax0.jamal.tools.FileTools(getInput:113)
	javax0.jamal.builtins.Include(getInputOptional:91)
	javax0.jamal.builtins.Include(evaluate:56)
	javax0.jamal.engine.Processor(evaluateBuiltinMacro:523)
	javax0.jamal.engine.Processor(lambda$evaluateBuiltInMacro$6:463)
	javax0.jamal.engine.Processor(safeEvaluate:472)
	javax0.jamal.engine.Processor(evaluateBuiltInMacro:463)
	javax0.jamal.engine.Processor(evalMacro:412)
	javax0.jamal.engine.Processor(processMacro:325)
	javax0.jamal.engine.Processor(process:202)
	javax0.jamal.asciidoc.JamalPreprocessor(processJamal:451)
	javax0.jamal.asciidoc.JamalPreprocessor(runJamalInProcess:288)
	javax0.jamal.asciidoc.JamalPreprocessor(process:205)
sed -i.bak  '' /Users/verhasp/github/turicum/clifx/REFERENCE.adoc.jam
----