package ch.turic.maven;

import org.w3c.dom.Document;
import org.xml.sax.InputSource;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

/**
 * The {@code PomXmlCreator} class provides functionality for converting a custom
 * 'pom.turi' file into a standard, well-formatted 'pom.xml' file, while handling
 * any processing, formatting, or writing errors that may occur. Additionally,
 * it includes utility methods for exception dumping and XML formatting.
 */
public class PomXmlCreator {

    // directories whose pom.xml was already generated in this Maven session. Maven calls
    // locatePom()/locateExistingPom() not only at session start but also mid-build; a pom
    // rewritten between maven-gpg-plugin signing it and the publishing plugin staging it
    // would invalidate the signature, so each pom is generated exactly once per session.
    private static final Set<String> GENERATED = ConcurrentHashMap.newKeySet();

    /**
     * Converts the 'pom.turi' file located in the specified directory into a formatted
     * 'pom.xml' file. The method reads, compiles, formats, and writes the XML output.
     * If the 'pom.turi' file is not found, an exception is thrown. Exceptions during
     * processing, formatting, or writing are also captured and re-thrown.
     * <p>
     * The generation is deterministic (the output carries no timestamp) and runs at most
     * once per directory per Maven session; when the generated content equals the existing
     * 'pom.xml', the file is not rewritten, so its modification time stays stable and
     * artifact signatures taken earlier in the build remain valid.
     *
     * @param directory the directory containing the 'pom.turi' file; must not be null
     *                  and should have read-write access, because the `pom.xml` will also be created there
     * @throws RuntimeException if the 'pom.turi' file is not found, cannot be processed,
     *                          cannot be formatted, or the output file cannot be written
     */
    static void turi2Xml(final File directory) {
        if (!GENERATED.add(directory.getAbsolutePath())) {
            return;
        }
        File turiFile = new File(directory, "pom.turi");
        if (!turiFile.exists()) {
            throw new RuntimeException("There is no 'pom.turi' file.");
        }

        final String fileName = turiFile.getAbsolutePath();
        final String xml;
        try (final var interpreter = new ch.turic.Interpreter(Path.of(fileName))) {
            xml = interpreter.compileAndExecute().toString();
        } catch (Exception e) {
            throw new RuntimeException("Jamal error processing the file " + fileName + "\n" + dumpException(e), e);
        }
        String formattedXml;
        try {
            final var lines = formatOutput(xml).split("\n", 2);
            formattedXml = lines[0] +
                    "\n<!-- Generated by: turicum maven extension -->\n" +
                    "<!-- Do not modify this file. Edit the 'pom.turi' instead -->\n" +
                    lines[1];
        } catch (Exception e) {
            throw new RuntimeException("Cannot format the file " + fileName + "\n" + dumpException(e), e);
        }

        final File output = new File(directory, "pom.xml");
        try {
            if (output.exists()
                    && formattedXml.equals(Files.readString(output.toPath(), StandardCharsets.UTF_8))) {
                return; // unchanged: keep the file byte-identical and its modification time intact
            }
        } catch (IOException ignored) {
            // unreadable existing file: fall through and (re)write it
        }
        // noinspection ResultOfMethodCallIgnored
        output.setWritable(true);
        try (final OutputStream os = new FileOutputStream(output)) {
            os.write(formattedXml.getBytes(StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new RuntimeException("Cannot write the 'pom.xml' file.", e);
        }
    }

    /**
     * Processes a throwable and its causes, collecting detailed information about the exception.
     * The method avoids circular references by tracking already-processed throwables using a set.
     * It gathers the throwable's message, stack trace, causes, and suppressed exceptions.
     *
     * @param e the throwable to be processed; can be null. If null, an empty string is returned.
     * @return a string representation of the throwable, including its message, stack trace,
     * causes, and suppressed exceptions.
     */
    private static String dumpException(Throwable e) {
        return dumpException(e, new HashSet<>());
    }

    /**
     * Recursively collects information about a throwable, including its message, stack trace,
     * causes, and suppressed exceptions, while avoiding circular references.
     *
     * @param e         the throwable to be processed; can be null.
     *                  If null or already processed, an empty string is returned.
     * @param processed a set of throwables that have already been processed to prevent
     *                  infinite recursion in case of circular references.
     * @return a string representation of the throwable, including its message and stack trace,
     * as well as information about its causes and suppressed exceptions.
     */
    private static String dumpException(Throwable e, Set<Throwable> processed) {
        if (e == null || processed.contains(e)) {
            return "";
        }
        processed.add(e);
        StringBuilder output = new StringBuilder();
        output.append(e.getMessage()).append("\n");
        try (final var sw = new StringWriter();
             final var pw = new PrintWriter(sw)) {
            e.printStackTrace(pw);
            output.append(sw);
        } catch (IOException ioException) {
            // does not happen, StringWriter does not do anything in close
        }
        output.append(dumpException(e.getCause(), processed));
        for (final Throwable t : e.getSuppressed()) {
            output.append(dumpException(t, processed));
        }
        return output.toString();
    }

    /**
     * Formats a given XML string by ensuring proper indentation and encoding.
     * This method parses the input XML string, transforms it into a structured
     * XML format with indentation, and removes any empty lines.
     *
     * @param result the input XML string to be formatted
     * @return the formatted XML string with proper indentation and encoding
     * @throws Exception if an error occurs during XML parsing or transformation
     */
    private static String formatOutput(String result) throws Exception {
        DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
        dbf.setValidating(false);
        DocumentBuilder db = dbf.newDocumentBuilder();
        Document doc = db.parse(new InputSource(new StringReader(result)));
        Transformer tf = TransformerFactory.newInstance().newTransformer();
        tf.setOutputProperty(OutputKeys.ENCODING, "UTF-8");
        tf.setOutputProperty(OutputKeys.INDENT, "yes");
        Writer out = new StringWriter();
        tf.transform(new DOMSource(doc), new StreamResult(out));
        return Arrays.stream(out.toString().split(System.lineSeparator())).filter(s -> !s.trim().isEmpty()).collect(Collectors.joining(System.lineSeparator()));
    }


}
