name: Packaging using jPackage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-13 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Build with Maven
        shell: bash
        run: mvn install -Dmaven.test.skip=true

      - name: Package Application
        run: python cli/package.py

      - name: Package Language Server
        run: python lsp/package.py

      # Linux upload Application
      - name: Upload Linux Package Application
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: linux-x64
          path: ./cli/output/*.deb

      # Linux upload Language Server
      - name: Upload Linux Package Language Server
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: linux-x64
          path: ./lsp/output/*.deb

      # Windows upload Application
      - name: Upload Windows Package Application
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-x64
          path: |
            ./cli/output/*.exe
            ./cli/output/*.msi

      # Windows upload Language Server
      - name: Upload Windows Package Language Server
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-x64
          path: |
            ./lsp/output/*.exe
            ./lsp/output/*.msi

      # macOS upload Application
      - name: Upload macOS Package Application
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-arm64
          path: ./cli/output/*.pkg

      # macOS upload Language Server
      - name: Upload macOS Package Language Server
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-arm64
          path: ./lsp/output/*.pkg

      # macOS Intel upload Application
      - name: Upload macOS Package Application
        if: matrix.os == 'macos-13'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-x64
          path: ./cli/output/*.pkg

      # macOS Intel upload Language Server
      - name: Upload macOS Package Language Server
        if: matrix.os == 'macos-13'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-x64
          path: ./lsp/output/*.pkg
