name: Packaging using jPackage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, macos-13 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Build with Maven
        run: mvn install -Dmaven.test.skip=true

      - name: Package Application
        run: python cli/package.py

      # Linux upload
      - name: Upload Linux Package
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: linux-x64
          path: ./cli/output/*.deb

      # Windows upload
      - name: Upload Windows Package
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-x64
          path: |
            ./cli/output/*.exe
            ./cli/output/*.msi

      # macOS upload
      - name: Upload macOS Package
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-arm64
          path: ./cli/output/*.pkg

      # macOS Intel upload
      - name: Upload macOS Package
        if: matrix.os == 'macos-13'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-x64
          path: ./cli/output/*.pkg
