name: Packaging using jPackage
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: {java-version: '21', distribution: temurin}
    - name: Package application
      run: sh ./cli/package.sh
    - name: Upload Package Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: linux-x64
        path: |
          output/*.deb
  windows-latest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: {java-version: '21', distribution: temurin}

    - name: Package application
      run: package.bat
      shell: cmd

    - name: Upload Log Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: turicum-post-image-log
        path: ${{ runner.temp }}/turicum-post-image.log

    - name: Upload Package Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: windows-x64
        path: |
          output/*.exe
          output/*.msi
  macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: {java-version: '21', distribution: temurin}
    - name: Package application
      run: sh ./cli/package.sh
    - name: Upload Package Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: macos-arm64
        path: |
          output/*.pkg
  macos-13:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: {java-version: '21', distribution: temurin}
    - name: Package application
      run: sh ./cli/package.sh
    - name: Upload Package Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: macos-x64
        path: |
          output/*.pkg
